### ISSUE TITLE
Mod Menu + Reaping Mod bug

### ISSUE THREAD

**Issue by didelphimorph** [JamCoreModding/OffhandOverhaul#1]
First, thanks for a great set of mods! Secondly, found what seems like a minor bug. I'm on Fabric 1.17 and I have v1.0.0 of this mod, v1.4.0 of Reaping Mod, and v2.0.2 of Mod Menu installed. When I'm using Mod Menu, the settings for Reaping Mod show up instead of Offhand Overhaul's settings. Reaping Mod's settings in Mod Menu seem to work normally, and changing Offhand's config by hand also works fine.

**Comment by Jamalam360** [comment]
That's a strange issue, thanks for reporting it, I'll try to fix it to tonight

**Comment by Jamalam360** [comment]
fixed in aa45378605404f4696eb45bf522955c3cf76be15
